import { keepPreviousData, useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ChevronLeft, ChevronRight, FileUp, Filter, Search } from 'lucide-react'
import { useMemo, useState } from 'react'
import { api } from '../api/client'
import { PageHeader, QueryState } from '../components/QueryState'
import { useI18n } from '../i18n/i18n'
import type { QuestionImportPreview, QuestionSummary } from '../types'

const q = (zh: string, en: string, locale: string) => locale === 'zh-CN' ? zh : en
const readFile = (file: File) => typeof file.text === 'function'
  ? file.text()
  : new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result || '')); reader.onerror = () => reject(reader.error); reader.readAsText(file) })

export function QuestionBankPage() {
  const { locale, t } = useI18n()
  const client = useQueryClient()
  const [page, setPage] = useState(1); const [search, setSearch] = useState(''); const [domain, setDomain] = useState(''); const [topic, setTopic] = useState(''); const [concept, setConcept] = useState(''); const [difficulty, setDifficulty] = useState(''); const [type, setType] = useState(''); const [status, setStatus] = useState('verified')
  const [importFile, setImportFile] = useState<{ filename: string; content: string } | null>(null); const [preview, setPreview] = useState<QuestionImportPreview | null>(null); const [fileError, setFileError] = useState<string | null>(null)
  const params = useMemo(() => { const p = new URLSearchParams({ page: String(page), page_size: '20', locale }); if (search) p.set('q', search); if (domain) p.set('domain', domain); if (topic) p.set('topic', topic); if (concept) p.set('concept', concept); if (difficulty) p.set('difficulty', difficulty); if (type) p.set('type', type); if (status) p.set(status, 'true'); return p }, [page, search, domain, topic, concept, difficulty, type, status, locale])
  const query = useQuery({ queryKey: ['questions', params.toString()], queryFn: () => api.questions(params), placeholderData: keepPreviousData, retry: 1 })
  const previewImport = useMutation({ mutationFn: () => api.previewQuestionImport(importFile!), onSuccess: setPreview })
  const commitImport = useMutation({ mutationFn: () => api.importQuestions(importFile!), onSuccess: () => { client.invalidateQueries({ queryKey: ['questions'] }); setPreview(null) } })
  const pages = Math.max(1, Math.ceil((query.data?.total || 0) / 20))
  const chooseFile = async (file: File | null) => { setPreview(null); setFileError(null); commitImport.reset(); previewImport.reset(); if (!file) { setImportFile(null); return }; if (!/\.(json|jsonl|ndjson)$/i.test(file.name)) { setFileError(q('请选择 .json、.jsonl 或 .ndjson 文件。', 'Choose a .json, .jsonl, or .ndjson file.', locale)); return }; setImportFile({ filename: file.name, content: await readFile(file) }) }
  return <div className="page">
    <PageHeader eyebrow="BANK / VERIFIED INVENTORY" title={t('nav.questions')} description={q('题库保留你的历史题目，并优先收录面试导向的双语题。可在此预览与导入按规范生成的 JSON/JSONL 包。', 'Your history stays intact while the bank prioritizes bilingual, interview-oriented questions. Preview and import spec-compliant JSON/JSONL packs here.', locale)} />
    <section className="import-panel panel"><div><span className="panel-code">LOCAL IMPORT / JSON · JSONL</span><h2>{q('导入外部题包', 'Import a question pack', locale)}</h2><p>{q('先做本地预览；只有整包通过校验后才会写入。已有 ID 不会覆盖历史题。', 'Preview locally first; the whole pack must validate before it is written. Existing IDs never overwrite history.', locale)}</p><p className="import-contract">{q('GPT 生成时：v2 双语 JSONL；选择题 A–D 同层级、长度相近、逐项解释不同误区，整包正确答案位置均衡；填空题提供两种语言可接受答案。完整合同见 docs/question-import-spec.md。', 'For GPT: emit bilingual v2 JSONL; A–D choices must be peer-level, comparable in length, each explain a distinct misconception, and answer positions balanced across the pack. Fill answers need accepted variants. Full contract: docs/question-import-spec.md.', locale)}</p></div><div className="import-actions"><label className="button ghost file-picker"><FileUp />{q('选择 JSON / JSONL', 'Choose JSON / JSONL', locale)}<input aria-label={q('选择 JSON 或 JSONL 文件', 'Choose JSON or JSONL file', locale)} type="file" accept=".json,.jsonl,.ndjson,application/json,application/x-ndjson" onChange={(event) => void chooseFile(event.target.files?.[0] || null)} /></label>{importFile && <small>{importFile.filename}</small>}<button className="button primary" disabled={!importFile || previewImport.isPending} onClick={() => previewImport.mutate()}>{previewImport.isPending ? q('正在预览…', 'Previewing…', locale) : q('预览导入', 'Preview import', locale)}</button></div>{fileError && <p className="inline-error">{fileError}</p>}{previewImport.error && <p className="inline-error">{previewImport.error.message}</p>}{preview && <ImportPreview preview={preview} locale={locale} onCommit={() => commitImport.mutate()} pending={commitImport.isPending} />}{commitImport.error && <p className="inline-error">{commitImport.error.message}</p>}{commitImport.data && <p className="import-success">{q(`已导入 ${commitImport.data.imported_count} 题；跳过 ${commitImport.data.skipped_count} 题。`, `${commitImport.data.imported_count} imported; ${commitImport.data.skipped_count} skipped.`, locale)}</p>}</section>
    <section className="filter-bar"><label className="search-box"><Search /><input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1) }} placeholder={q('搜索题干 / concept', 'Search prompt / concept', locale)} /></label><Filter /><Select value={domain} set={setDomain} label="DOMAIN" values={['', 'sde', 'mle']} /><FilterInput value={topic} set={setTopic} label="TOPIC" /><FilterInput value={concept} set={setConcept} label="CONCEPT" /><Select value={difficulty} set={setDifficulty} label="LEVEL" values={['', 'L1', 'L2', 'L3']} /><Select value={type} set={setType} label="TYPE" values={['', 'single_choice', 'fill_blank']} /><Select value={status} set={setStatus} label="STATE" values={['verified', 'never_attempted', 'wrong_before', 'bookmarked']} /></section>
    <QueryState loading={query.isLoading} error={query.error} retry={() => query.refetch()}>{query.data && <><div className="bank-table"><div className="bank-head"><span>ID / PROMPT</span><span>DOMAIN</span><span>TOPIC / CONCEPT</span><span>LEVEL</span><span>TYPE</span></div>{query.data.items.map((item) => <QuestionRow key={item.id} item={item} />)}</div><footer className="pagination"><span>{query.data.total} ITEMS</span><button disabled={page === 1} onClick={() => setPage((p) => p - 1)}><ChevronLeft /></button><b>{page} / {pages}</b><button disabled={page >= pages} onClick={() => setPage((p) => p + 1)}><ChevronRight /></button></footer></>}</QueryState>
  </div>
}

function ImportPreview({ preview, locale, onCommit, pending }: { preview: QuestionImportPreview; locale: string; onCommit: () => void; pending: boolean }) { const canCommit = preview.invalid_count === 0 && preview.valid_count > 0; return <div className="import-preview"><div><b>{q(`有效 ${preview.valid_count}`, `${preview.valid_count} valid`, locale)}</b><span>{q(`无效 ${preview.invalid_count}`, `${preview.invalid_count} invalid`, locale)}</span><span>{q(`重复 ${preview.duplicate_count}`, `${preview.duplicate_count} duplicates`, locale)}</span></div>{preview.errors.length > 0 && <ul>{preview.errors.slice(0, 6).map((issue, index) => <li key={`${issue.line || index}-${issue.message}`}>{issue.line ? `${q('第', 'Line ', locale)}${issue.line}${q(' 行：', ': ', locale)}` : ''}{issue.message}</li>)}</ul>}<button className="button primary" disabled={!canCommit || pending} onClick={onCommit}>{pending ? q('正在导入…', 'Importing…', locale) : q('确认导入', 'Confirm import', locale)}</button></div> }
function QuestionRow({ item }: { item: QuestionSummary }) { return <article><div><small>{item.id}</small><strong>{item.prompt}</strong>{(item.question_style || item.quality_tier || item.source_kind) && <div className="question-badges">{item.question_style && <span>{item.question_style.replace('_', ' ').toUpperCase()}</span>}{(item.quality_tier || item.source_kind) && <span>{(item.quality_tier || item.source_kind || '').toUpperCase()}</span>}</div>}</div><b>{item.domain.toUpperCase()}</b><span>{item.topic}<small>{item.concept}</small></span><em className={`level ${item.difficulty}`}>{item.difficulty}</em><span>{item.type === 'single_choice' ? 'CHOICE' : 'FILL'}</span></article> }
function Select({ value, set, label, values }: { value: string; set: (v: string) => void; label: string; values: string[] }) { return <label className="compact-select"><span>{label}</span><select value={value} onChange={(e) => set(e.target.value)}>{values.map((v) => <option key={v} value={v}>{v || 'ALL'}</option>)}</select></label> }
function FilterInput({ value, set, label }: { value: string; set: (v: string) => void; label: string }) { return <label className="compact-select compact-input"><span>{label}</span><input value={value} onChange={(event) => set(event.target.value)} placeholder="ALL" /></label> }
