import { useQuery } from '@tanstack/react-query'
import { Check, ChevronDown, Clock3, X } from 'lucide-react'
import { useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { api } from '../api/client'
import { PageHeader, QueryState } from '../components/QueryState'
import { useI18n } from '../i18n/i18n'

const pct = (value: number) => `${Math.round(value <= 1 ? value * 100 : value)}%`
export function ResultPage() {
  const { id = '' } = useParams(); const { t, locale } = useI18n(); const query = useQuery({ queryKey: ['result', id], queryFn: () => api.result(id), retry: 1 }); const [open, setOpen] = useState<number | null>(0)
  return <div className="page"><PageHeader eyebrow="POST-EXAM / ANALYSIS" title={locale === 'zh-CN' ? '结果与逐题解析' : 'Results & debrief'} description={locale === 'zh-CN' ? '分数是结果，错误结构才是下一套卷的输入。' : 'The score is an output. Error structure drives the next paper.'}/><QueryState loading={query.isLoading} error={query.error} retry={() => query.refetch()}>{query.data && <>
    <section className="score-board"><div className="score-main"><small>SCORE</small><strong>{query.data.score}<span> / {query.data.total_score}</span></strong></div><div><small>CORRECT</small><strong className="good">{query.data.correct_count} / {query.data.total_questions}</strong></div><div><small>TIME</small><strong><Clock3/>{Math.floor(query.data.elapsed_seconds / 60)}:{String(query.data.elapsed_seconds % 60).padStart(2, '0')}</strong></div><div><small>CHOICE / FILL</small><strong>{pct(query.data.choice_accuracy)} · {pct(query.data.fill_accuracy)}</strong></div></section>
    {query.data.next_exam_id && <div className="resume-strip"><span>{locale === 'zh-CN' ? `连续套卷 ${query.data.paper_index} / ${query.data.paper_count} 已完成` : `Paper ${query.data.paper_index} of ${query.data.paper_count} complete`}</span><Link className="button primary" to={`/exam/${query.data.next_exam_id}`}>{locale === 'zh-CN' ? '开始下一套' : 'Start next paper'}</Link></div>}
    <div className="breakdown-grid"><Breakdown title={locale === 'zh-CN' ? '按难度' : 'By difficulty'} data={query.data.difficulty_breakdown}/><Breakdown title={locale === 'zh-CN' ? '按知识点' : 'By topic'} data={query.data.topic_breakdown}/></div>
    <section className="review-list"><div className="section-title"><span>QUESTION DEBRIEF</span><h2>{locale === 'zh-CN' ? '逐题解析' : 'Question review'}</h2></div>{query.data.questions.map((question, index) => <article key={question.id} className={`review-item ${question.correct ? 'correct' : 'wrong'}`}><button className="review-summary" onClick={() => setOpen(open === index ? null : index)}><span className="result-icon">{question.correct ? <Check/> : <X/>}</span><b>{String(question.position).padStart(2, '0')}</b><p>{question.prompt}</p><em>{question.difficulty}</em><ChevronDown/></button>{open === index && <div className="review-detail"><dl><div><dt>{t('result.yourAnswer')}</dt><dd>{question.user_answer || '—'}</dd></div><div><dt>{t('result.correctAnswer')}</dt><dd>{question.correct_answer}</dd></div></dl><h3>{t('result.explanation')}</h3><p>{question.explanation}</p><TargetedDistractor answer={question.user_answer} correct={question.correct} explanations={question.distractor_explanations} locale={locale}/>{question.takeaway && <p className="takeaway"><b>{locale === 'zh-CN' ? '带走一句：' : 'Takeaway: '}</b>{question.takeaway}</p>}{question.knowledge_card && <KnowledgeCard card={question.knowledge_card} locale={locale}/>}<footer>{question.topic} / {question.concept} · {locale === 'zh-CN' ? `历史 ${question.attempt_count || 1} 次` : `${question.attempt_count || 1} lifetime attempts`}</footer></div>}</article>)}</section>
  </>}</QueryState></div>
}
function Breakdown({ title, data }: { title: string; data: Record<string, number> }) { return <section className="panel breakdown"><span className="panel-code">{title}</span>{Object.entries(data).map(([key, value]) => <div key={key}><span>{key}</span><div className="bar"><i style={{ width: pct(value) }}/></div><strong>{pct(value)}</strong></div>)}</section> }

function TargetedDistractor({ answer, correct, explanations, locale }: { answer?: string | null; correct: boolean; explanations?: Record<string, string>; locale: string }) { const explanation = !correct && answer ? explanations?.[answer] : undefined; if (!explanation) return null; return <div className="targeted-distractor"><b>{locale === 'zh-CN' ? `你选的 ${answer} 为什么不对` : `Why your ${answer} answer is wrong`}</b><p>{explanation}</p></div> }
function KnowledgeCard({ card, locale }: { card: { summary?: string; why_it_matters?: string; interview_angle?: string; common_pitfall?: string }; locale: string }) { const rows = [[locale === 'zh-CN' ? '核心概念' : 'Core concept', card.summary], [locale === 'zh-CN' ? '为什么重要' : 'Why it matters', card.why_it_matters], [locale === 'zh-CN' ? '面试表达' : 'Interview angle', card.interview_angle], [locale === 'zh-CN' ? '常见误区' : 'Common pitfall', card.common_pitfall]].filter(([, value]) => Boolean(value)); if (!rows.length) return null; return <aside className="knowledge-card"><span>KNOWLEDGE CARD</span>{rows.map(([label, value]) => <p key={label}><b>{label}</b>{value}</p>)}</aside> }
