import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { CheckCircle2, RefreshCw, Shield } from 'lucide-react'
import { useEffect, useState } from 'react'
import { api } from '../api/client'
import { PageHeader, QueryState } from '../components/QueryState'
import { LocaleToggle, useI18n } from '../i18n/i18n'

export function SettingsPage() {
  const { locale, t } = useI18n(); const client = useQueryClient(); const settings = useQuery({ queryKey:['settings'],queryFn:api.settings,retry:1}); const providers = useQuery({queryKey:['providers'],queryFn:api.providerStatus,retry:1}); const [goal,setGoal]=useState('160'); useEffect(()=>{if(settings.data?.daily_target!==undefined)setGoal(String(settings.data.daily_target ?? 'unlimited'))},[settings.data]); const save=useMutation({mutationFn:()=>api.saveSettings({locale,daily_target:goal==='unlimited'?0:Number(goal)}),onSuccess:()=>client.invalidateQueries({queryKey:['settings']})}); const test=useMutation({mutationFn:api.testProviders,onSuccess:()=>client.invalidateQueries({queryKey:['providers']})})
  return <div className="page"><PageHeader eyebrow="SYSTEM / LOCAL CONFIG" title={t('nav.settings')} description={locale==='zh-CN'?'这里只保存训练偏好。Provider 密钥不会进入浏览器或 SQLite。':'Only training preferences live here. Provider secrets never enter the browser or SQLite.'}/><div className="settings-grid"><section className="panel settings-panel"><span className="panel-code">INTERFACE</span><h2>{t('settings.language')}</h2><LocaleToggle/><h2>{t('settings.goal')}</h2><div className="segment wrap">{['40','80','120','160','200','unlimited'].map(v=><button key={v} className={goal===v?'selected':''} onClick={()=>setGoal(v)}>{v==='unlimited'?'∞':v}</button>)}</div><button className="button primary" onClick={()=>save.mutate()} disabled={save.isPending}>{save.isSuccess?<><CheckCircle2/>SAVED</>:locale==='zh-CN'?'保存偏好':'Save preferences'}</button></section><section className="panel settings-panel"><div className="provider-title"><div><span className="panel-code">DECISION ROUTER</span><h2>{t('settings.provider')}</h2></div><button className="icon-button" aria-label="Test providers" onClick={()=>test.mutate()}><RefreshCw/></button></div><QueryState loading={providers.isLoading} error={providers.error} retry={()=>providers.refetch()}>{providers.data&&<div className="providers"><Provider name="JEV" state={providers.data.jev}/><Provider name="NANOJEV" state={providers.data.nanojev}/><Provider name="VON" state={providers.data.von}/><div className="active-provider"><span>ACTIVE PROVIDER</span><strong>{providers.data.active_provider}</strong></div></div>}</QueryState><p className="adaptation-note">{locale==='zh-CN'?'Jev 只根据作答表现调整难度与知识覆盖，不会替换你在建卷时选择的 A / D / G 卷型。':'Jev adjusts difficulty and knowledge coverage from your performance only. It cannot change the A / D / G template you selected.'}</p><p className="adaptation-note">{locale==='zh-CN'?'触发点：新卷开始前确定下一卷的难度配比；交卷后为下一卷更新覆盖重点；Rapid 每答 10 题重排后续 10 题。Jev 不生成、翻译或判定题目内容。':'Trigger points: before a new exam for its difficulty mix; after submission for the next exam coverage; and every 10 Rapid answers for the following block. Jev does not write, translate, or grade question content.'}</p><p className="secret-note"><Shield/>{t('settings.secret')}</p></section></div></div>
}
function Provider({name,state}:{name:string;state:string}){const good=['connected','running'].includes(state);return <div className="provider-row"><span><i className={good?'good':''}/>{name}</span><b>{state.replace('_',' ').toUpperCase()}</b></div>}
